In [1]:
import geopandas as gpd
from glob import glob
import pandas as pd
DATADIR = '/data/uscuni-ulce/buildings_raw/'

In [2]:
regions = [
    
# "buildings_austria*",
# "buildings_slovakia*",
# "buildings_poland*",
# "buildings_czechia*",
# "buildings_germany"
]

In [3]:
eubucco_regions = [
    # '/data/uscuni-ulce/eubucco_raw/v0_1-AUT*',
    # '/data/uscuni-ulce/eubucco_raw/v0_1-SVK*',
    # '/data/uscuni-ulce/eubucco_raw/v0_1-POL*',
    # '/data/uscuni-ulce/eubucco_raw/v0_1-CZE*',
]


In [9]:
for region, eubucco_region in zip(regions, eubucco_regions):
    
    files = glob(DATADIR + region)
    frames = []
    for f in files:
        gdf = gpd.read_parquet(f)
        if gdf.shape[0]:
            frames.append(gdf.to_crs(epsg=3035))
    gdf = pd.concat(frames, ignore_index=True)


    files = glob(eubucco_region)
    frames = []
    for f in files:
        gdf1 = gpd.read_file(f)
        if gdf1.shape[0]:
            frames.append(gdf1)
    eubucco_gdf = pd.concat(frames, ignore_index=True)

    print(gdf.shape, eubucco_gdf.shape)
    break

(4274434, 36) (4044659, 7)


In [11]:
gdf.to_parquet('/data/uscuni-ulce/buildings_standardised/buildings_czechia.pq')

In [10]:
DATADIR + region

'/data/uscuni-ulce/buildings_raw/buildings_czechia*'

In [50]:
# (4427904, 30) (4135733, 7)
# (3563020, 31) (3488125, 7)
# (15387645, 14) (14404767, 7)
# (4274434, 36) (4044659, 7)

In [14]:
ger_regions = ['bavaria', 'brandeburg', 'bw', 'hessen', 'mv',
       'nrw', 'rlp', 'saarland', 'sachsen', 'sachsen-anhalt', 'sg', 
       'th', 'ni', 'bremen', 'hamburg', 'berlin']
# bayern - no function
# bb -function
# bw - function
# hessen - function

###### germany

In [69]:
files = glob('/data/uscuni-ulce/buildings_standardised/buildings_germany*')
for f in files:
    gdf = gpd.read_parquet(f)
    if gdf.shape[0]:
        frames.append(gdf.to_crs(epsg=3035))
gdf = pd.concat(frames, ignore_index=True)

/tmp/ipykernel_245062/807000398.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  gdf = pd.concat(frames, ignore_index=True)


In [73]:
gdf.shape

(60512650, 61)

In [3]:
files = glob('/data/uscuni-ulce/eubucco_raw/v0_1-DEU*')
frames = []
for f in files:
    gdf1 = gpd.read_file(f)
    if gdf1.shape[0]:
        frames.append(gdf1)
eubucco_gdf = pd.concat(frames, ignore_index=True)

In [4]:
eubucco_gdf.shape

(43644887, 7)

In [29]:
ger_regions = ['bavaria', 'brandeburg', 'bw', 'hessen', 'mv',
       'nrw', 'rlp', 'saarland', 'sachsen', 'sachsen-anhalt', 'sg', 
       'th', 'ni', 'bremen', 'hamburg', 'berlin']
# bayern - no function
# bb -function
# bw - function
# hessen - function

In [16]:
for r in ger_regions:

    gdf = gpd.read_parquet(f'/data/uscuni-ulce/buildings_standardised/buildings_germany_{r}.pq')
    break

In [23]:
gdf['ags'].unique()

array([9571224, 9571179, 9571136, ..., 9779130, 9779452, 9779180],
      dtype=int32)

In [ ]:
# bad - hessen(waiting), mv(continue from where it broke)
## sh(schesig hollstein is sg)

In [4]:
ger_eubucco = '/data/uscuni-ulce/eubucco_raw/v0_1-DEU_*'

len(ger_regions)

16

In [9]:
region = ger_regions[0]
region

'bavaria'

In [10]:
files = glob(f'{DATADIR}buildings_germany_{region}*')

In [11]:
sorted(files)[:10]

['/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_mittelfranken.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_niederbayern.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_oberbayern.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_overfranken.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_overpfalz.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_schwaben.pq',
 '/data/uscuni-ulce/buildings_raw/buildings_germany_bavaria_unterfranken.pq']

In [12]:
len(files)

7

In [13]:
frames = []
for f in files:
    gdf = gpd.read_parquet(f)
    if gdf.shape[0]:
        frames.append(gdf.to_crs(epsg=3035))


In [59]:
gdf = pd.concat(frames, ignore_index=True)
# if 'gml_id' in gdf.columns:
#     gdf = gdf[~gdf['gml_id'].duplicated()]
# if 'oid' in gdf.columns:
#     gdf = gdf[~gdf['oid'].duplicated()]

In [60]:
gdf.shape

(1400000, 13)

In [64]:
import numpy as np
np.unique(gdf['gebnutzbez'], return_counts=True)

(array(['Bauteil', 'Gebäude',
        'Sonstiges Bauwerk oder sonstige Einrichtung', 'Turm'],
       dtype=object),
 array([  69560, 1313565,   16748,     127]))

In [13]:
gdf.to_parquet(f'/data/uscuni-ulce/buildings_standardised/buildings_germany_{region}.pq')

In [20]:
import requests
import re
def get_size(url, params):
    params = params.copy()
    params['resultType'] = 'hits'
    response = requests.get(url, params=params)
    if response.status_code == 200:
        size = re.findall(r'numberMatched="[0-9]+"', str(response.content))
        size = int(size[0].split('=')[-1][1:-1])
        return size

    return 'unknown'

In [21]:
params = {
        "SERVICE": "WFS",
        "REQUEST": "GetFeature",
        "TYPENAMES": "bu-core2d:Building",
        "SRSNAME": "EPSG:4326",
        "VERSION": '2.0.0',
    }
url = 'https://inspire-hessen.de/ows/services/org.2.29e99e26-ab08-474a-92c4-9e8f6bc679ea_wfs?'

size = get_size(url, params)
print(size)

4997363


In [134]:
response = requests.get('https://www.geodaten-mv.de/dienste/inspire_au_alkis_download?SERVICE=WFS&REQUEST=Getfeature&typenames=au:AdministrativeUnit&VERSION=2.0.0')

In [135]:
from io import BytesIO

In [143]:
r = gpd.read_file(BytesIO(response.content))

/home/krasen/miniconda3/envs/urban_taxonomy/lib/python3.12/site-packages/pyogrio/raw.py:196: RuntimeWarning: Field with same name (identifier) already exists in (AdministrativeUnit). Skipping newer ones
  return ogr_read(


In [145]:
r.nationalCode.values

array([      13,    13076,    13075,    13072,    13071,    13074,
          13073,    13004,    13003, 13076146, 13076147, 13076048,
       13076129, 13076153, 13076133, 13076044, 13076051, 13076056,
       13076085, 13076082, 13074084, 13076088, 13004000, 13076090,
       13076072, 13076089, 13076162, 13076075, 13076164, 13076077,
       13076118, 13076138, 13076107, 13076110, 13076105, 13076131,
       13076106, 13076136, 13076143, 13076145, 13076111, 13076141,
       13076097, 13076121, 13076115, 13076142, 13076094, 13076119,
       13076078, 13076023, 13076116, 13076024, 13076103, 13076130,
       13076102, 13076099, 13076032, 13076109, 13076098, 13076122,
       13076033, 13076112, 13076062, 13076113, 13076114, 13076026,
       13076101, 13076025, 13076080, 13076029, 13076108, 13076104,
       13076006, 13076079, 13076005, 13076087, 13076011, 13076020,
       13076007, 13076093, 13076015, 13076076, 13076073, 13076152,
       13076016, 13076148, 13076092, 13076014, 13076017, 13076

In [153]:
code = 13076146
dl_url = f'https://www.geodaten-mv.de/dienste/alkis_wfs_einfach?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&CRS=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A25833&OUTPUTFORMAT=application%2Fx-zip-shapefile&STOREDQUERY_ID=http%3A%2F%2Frepository.gdi-de.org%2Fquery%2Fadv%2Fprodukt%2Falkis-vereinfacht%2F2.0%2Fflst-by-gemarkung&GEMARKUNGSNUMMER={code}'
dl_url

'https://www.geodaten-mv.de/dienste/alkis_wfs_einfach?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&CRS=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A25833&OUTPUTFORMAT=application%2Fx-zip-shapefile&STOREDQUERY_ID=http%3A%2F%2Frepository.gdi-de.org%2Fquery%2Fadv%2Fprodukt%2Falkis-vereinfacht%2F2.0%2Fflst-by-gemarkung&GEMARKUNGSNUMMER=13076146'

In [154]:
!wget https://www.geodaten-mv.de/dienste/alkis_wfs_einfach?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&CRS=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A25833&OUTPUTFORMAT=application%2Fx-zip-shapefile&STOREDQUERY_ID=http%3A%2F%2Frepository.gdi-de.org%2Fquery%2Fadv%2Fprodukt%2Falkis-vereinfacht%2F2.0%2Fflst-by-gemarkung&GEMARKUNGSNUMMER=13076146

In [147]:
response = requests.get(dl_url)

In [148]:
response.status_code

200

In [152]:
gdf = gpd.read_file(BytesIO(response.content))

DataSourceError: '/vsizip//vsimem/371cb5c32a3141618558500fc084cb07.zip' not recognized as being in a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.

In [6]:
gdf = gpd.read_parquet(files[0])

In [18]:
new_gdf = gdf.set_crs(epsg=25832).to_crs(epsg=3035)

In [21]:
# new_gdf.iloc[100000:101000].explore()

In [37]:
frames = []
for f in files:
    frames.append(gpd.read_parquet(f).to_crs(epsg=3035))
gdf = pd.concat(frames, ignore_index=True)

KeyboardInterrupt: 

In [ ]:
gdf

In [10]:
gpd.read_parquet(f)

gml_id  \
0       Building_DEHHALKA3wT000D2   
1       Building_DEHHALKA3wT000D0   
2       Building_DEHHALKA3xh000Id   
3       Building_DEHHALKA3D1000Ih   
4       Building_DEHHALKA3xh000Is   
...                           ...   
454566  Building_DEHHALKAn0007tva   
454567  Building_DEHHALKA4YR00007   
454568  Building_DEHHALKA4YR00003   
454569  Building_DEHHALKAn0007tvb   
454570  Building_DEHHALKA4YR00005   

                                               identifier  \
0       https://registry.gdi-de.org/id/de.hh/e33c193f-...   
1       https://registry.gdi-de.org/id/de.hh/e33c193f-...   
2       https://registry.gdi-de.org/id/de.hh/e33c193f-...   
3       https://registry.gdi-de.org/id/de.hh/e33c193f-...   
4       https://registry.gdi-de.org/id/de.hh/e33c193f-...   
...                                                   ...   
454566  https://registry.gdi-de.org/id/de.hh/e33c193f-...   
454567  https://registry.gdi-de.org/id/de.hh/e33c193f-...   
454568  https://registry.gdi-de.org/id/de.hh/e33c193f-...   
454569  https://registry.gdi-de.org/id/de.hh/e33c193f-...   
454570  https://registry.gdi-de.org/id/de.hh/e33c193f-...   

        beginLifespanVersion                    localId  \
0       2018-05-24T08:48:56Z  Building_DEHHALKA3wT000D2   
1       2018-05-24T08:48:56Z  Building_DEHHALKA3wT000D0   
2       2018-05-31T10:07:45Z  Building_DEHHALKA3xh000Id   
3       2017-08-15T09:52:04Z  Building_DEHHALKA3D1000Ih   
4       2018-05-31T10:07:45Z  Building_DEHHALKA3xh000Is   
...                      ...                        ...   
454566  2012-04-02T07:54:53Z  Building_DEHHALKAn0007tva   
454567  2019-01-11T05:21:25Z  Building_DEHHALKA4YR00007   
454568  2019-07-03T13:37:37Z  Building_DEHHALKA4YR00003   
454569  2012-04-02T07:54:53Z  Building_DEHHALKAn0007tvb   
454570  2019-01-11T05:21:25Z  Building_DEHHALKA4YR00005   

                                                namespace percentage  \
0       https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
1       https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
2       https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
3       https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
4       https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
...                                                   ...        ...   
454566  https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
454567  https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
454568  https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
454569  https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   
454570  https://registry.gdi-de.org/id/de.hh/e33c193f-...       None   

        referenceGeometry horizontalGeometryEstimatedAccuracy  \
0                    True                                None   
1                    True                                None   
2                    True                                None   
3                    True                                None   
4                    True                                None   
...                   ...                                 ...   
454566               True                                None   
454567               True                                None   
454568               True                                None   
454569               True                                None   
454570               True                                None   

        numberOfFloorsAboveGround                   end  \
0                             NaN                  None   
1                             NaN                  None   
2                             NaN                  None   
3                             NaN                  None   
4                             NaN                  None   
...                           ...                   ...   
454566                        1.0                  None   
454567                